### ISSUE TITLE
ModuleNotFoundError: No module named 'smbus' on raspbian bullseye - missing dependencies?

### ISSUE THREAD

**Issue by lamasek** [pimoroni/lsm303d-python#8]
Hi,

I bougt pimoroni LSM303d, but I was not able to make it working.
I made python3 -m pip install lsm303d
and when I am executing:
   python3 magnetometer.py #(copy of https://github.com/pimoroni/lsm303d-python/blob/master/examples/magnetometer.py)
Result is:
Traceback (most recent call last):
  File "/home/pi/lsm303d/magnetometer.py", line 7, in <module>
    lsm = LSM303D(0x1d) # Change to 0x1e if you have soldered the address jumper
  File "/home/pi/.local/lib/python3.9/site-packages/lsm303d/__init__.py", line 38, in __init__
    self._lsm303d = Device([0x1D, 0x1E], i2c_dev=self._i2c_dev, bit_width=8, registers=(
  File "/home/pi/.local/lib/python3.9/site-packages/i2cdevice/__init__.py", line 165, in __init__
    import smbus
ModuleNotFoundError: No module named 'smbus'

I fix it by:
  pip3 install smbus

I am using Raspberry pi Zero W, with Raspbian 11 bullseye.

And then sudo raspi-config, Interfacing options->I2C choose, enable I2C, reboot, ....

Thanks, Joseph

**Comment by Gadgetoid** [comment]
I believe this has been fixed.
